name = input('Enter your name: ')
age = int(input('How old are you? '))
country = input('which country are you from? ')
height = float(input('enter your height in cm: '))
 
print(f'=======================================')
print(f'        PERSONAL BIO CARD')
print(f'=======================================')
print(f'Name:,         {name}')
print(f'Age:,          {age}')
print(f'Country:,      {country}')
print(f'Height:,       {height}cm')
print(f'========================================')