client = input("Enter your client's name: ")
item = input("Enter the item: ")
hours = float(input('Enter hours: '))
rate = float(input('Enter rate: '))
subtotal = rate * hours
tax = subtotal * (7.5 / 100)
total = subtotal + tax

print('=============================')
print('\tINVOICE')
print('=============================')
print(f'Client:     {client}')
print(f'Item:       {item}')
print(f'Hours:      {hours}')
print(f'Rate:       ${rate:.2f}')
print('------------------------------')
print(f'Subtotal:   ${subtotal:.2f}')
print(f'Tax (7.5%): ${tax:.2f}')
print(f'Total:      ${total:.2f}')
print('===============================')